<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Provides the enriched council list matching the React app's Council interface.
 *
 * Each entry has: name, region, nation.
 * This mirrors react/src/data/councils.ts exactly so the React app's
 * nation filter chips and region grouping work identically.
 */
class PIC_CouncilData
{
    /**
     * Returns the full council list shaped to match the React Council interface.
     *
     * @return array<int, array{name: string, region: string, nation: string}>
     */
    public static function all(): array
    {
        return self::$councils;
    }

    /**
     * Returns the list of nations used for filter chips.
     *
     * @return string[]
     */
    public static function nations(): array
    {
        return ['England', 'Scotland', 'Wales', 'Northern Ireland'];
    }

    /**
     * Returns the unique sorted list of regions.
     *
     * @return string[]
     */
    public static function regions(): array
    {
        $regions = [];
        foreach (self::$councils as $council) {
            $regions[$council['region']] = true;
        }
        $regions = array_keys($regions);
        sort($regions);
        return $regions;
    }

    /**
     * @var array<int, array{name: string, region: string, nation: string}>
     */
    private static array $councils = [
        // England - Greater London
        ['name' => 'City of London Corporation', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Barking and Dagenham', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Barnet', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Bexley', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Brent', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Bromley', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Camden', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Croydon', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Ealing', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Enfield', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Greenwich', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Hackney', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Hammersmith and Fulham', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Haringey', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Harrow', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Havering', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Hillingdon', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Hounslow', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Islington', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Kensington and Chelsea', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Kingston upon Thames', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Lambeth', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Lewisham', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Merton', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Newham', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Redbridge', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Richmond upon Thames', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Southwark', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Sutton', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Tower Hamlets', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Waltham Forest', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Wandsworth', 'region' => 'Greater London', 'nation' => 'England'],
        ['name' => 'Westminster', 'region' => 'Greater London', 'nation' => 'England'],

        // England - North East
        ['name' => 'County Durham', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Darlington', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Gateshead', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Hartlepool', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Middlesbrough', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Newcastle upon Tyne', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'North Tyneside', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Northumberland', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Redcar and Cleveland', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'South Tyneside', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Stockton-on-Tees', 'region' => 'North East', 'nation' => 'England'],
        ['name' => 'Sunderland', 'region' => 'North East', 'nation' => 'England'],

        // England - North West
        ['name' => 'Allerdale', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Barrow-in-Furness', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Blackburn with Darwen', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Blackpool', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Bolton', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Burnley', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Bury', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Carlisle', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Cheshire East', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Cheshire West and Chester', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Chorley', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Copeland', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Eden', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Fylde', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Halton', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Hyndburn', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Knowsley', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Lancaster', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Liverpool', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Manchester', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Oldham', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Pendle', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Preston', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Ribble Valley', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Rochdale', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Rossendale', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'St Helens', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Salford', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Sefton', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'South Lakeland', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'South Ribble', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Stockport', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Tameside', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Trafford', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Warrington', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'West Lancashire', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Wigan', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Wirral', 'region' => 'North West', 'nation' => 'England'],
        ['name' => 'Wyre', 'region' => 'North West', 'nation' => 'England'],

        // England - Yorkshire and the Humber
        ['name' => 'Barnsley', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Bradford', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Calderdale', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Craven', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Doncaster', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'East Riding of Yorkshire', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Hambleton', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Harrogate', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Hull', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Kirklees', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Leeds', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'North East Derbyshire', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Richmondshire', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Rotherham', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Ryedale', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Scarborough', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Selby', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Sheffield', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'Wakefield', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],
        ['name' => 'York', 'region' => 'Yorkshire and the Humber', 'nation' => 'England'],

        // England - East Midlands
        ['name' => 'Amber Valley', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Ashfield', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Bassetlaw', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Blaby', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Bolsover', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Broxtowe', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Charnwood', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Chesterfield', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Corby', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Daventry', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Derby', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Derbyshire Dales', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Erewash', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Gedling', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Harborough', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Hinckley and Bosworth', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Kettering', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Leicester', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Lincoln', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Mansfield', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Melton', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Newark and Sherwood', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Northampton', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'North West Leicestershire', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Nottingham', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Oadby and Wigston', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Rugby', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Rushcliffe', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'South Derbyshire', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'South Northamptonshire', 'region' => 'East Midlands', 'nation' => 'England'],
        ['name' => 'Wellingborough', 'region' => 'East Midlands', 'nation' => 'England'],

        // England - West Midlands
        ['name' => 'Birmingham', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Bromsgrove', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Cannock Chase', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Coventry', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Dudley', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'East Staffordshire', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Herefordshire', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Lichfield', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Malvern Hills', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Newcastle-under-Lyme', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Nuneaton and Bedworth', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Redditch', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Rugby', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Sandwell', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Shropshire', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Solihull', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'South Staffordshire', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Stafford', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Staffordshire Moorlands', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Stoke-on-Trent', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Stratford-on-Avon', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Tamworth', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Walsall', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Warwick', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Wolverhampton', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Worcester', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Wychavon', 'region' => 'West Midlands', 'nation' => 'England'],
        ['name' => 'Wyre Forest', 'region' => 'West Midlands', 'nation' => 'England'],

        // England - East of England
        ['name' => 'Babergh', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Basildon', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Bedford', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Braintree', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Breckland', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Brentwood', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Broadland', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Broxbourne', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Cambridge', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Castle Point', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Central Bedfordshire', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Chelmsford', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Colchester', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Dacorum', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'East Cambridgeshire', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'East Hertfordshire', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'East Suffolk', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Epping Forest', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Forest Heath', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Great Yarmouth', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Harlow', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Hertsmere', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Ipswich', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'King\'s Lynn and West Norfolk', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Maldon', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Mid Suffolk', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Mid Sussex', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'North Norfolk', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'North Hertfordshire', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Norwich', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Peterborough', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Rochford', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'South Cambridgeshire', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'South Norfolk', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'South Suffolk', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'St Albans', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Stevenage', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Suffolk Coastal', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Tendring', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Three Rivers', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Thurrock', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Uttlesford', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Watford', 'region' => 'East of England', 'nation' => 'England'],
        ['name' => 'Welwyn Hatfield', 'region' => 'East of England', 'nation' => 'England'],

        // England - South East
        ['name' => 'Adur', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Arun', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Ashford', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Aylesbury Vale', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Basingstoke and Deane', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Bracknell Forest', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Cherwell', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Chichester', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Chiltern', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Crawley', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Dartford', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Dover', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'East Hampshire', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Eastbourne', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Eastleigh', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Epsom and Ewell', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Fareham', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Folkestone and Hythe', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Gosport', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Gravesham', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Guildford', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Hart', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Hastings', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Havant', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Horsham', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Isle of Wight', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Lewes', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Maidstone', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Mole Valley', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'New Forest', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Oxford', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Portsmouth', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Reading', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Reigate and Banstead', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Rother', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Runnymede', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Rushmoor', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Sevenoaks', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Shepway', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Slough', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'South Buckinghamshire', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'South Oxfordshire', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Southampton', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Spelthorne', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Surrey Heath', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Tandridge', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Tunbridge Wells', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Vale of White Horse', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Wealden', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Waverley', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Wealden', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'West Berkshire', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'West Oxfordshire', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Winchester', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Windsor and Maidenhead', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Woking', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Wokingham', 'region' => 'South East', 'nation' => 'England'],
        ['name' => 'Worthing', 'region' => 'South East', 'nation' => 'England'],

        // England - South West
        ['name' => 'Bath and North East Somerset', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Bournemouth', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Bristol', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Cheltenham', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Christchurch', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Cornwall', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Cotswold', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Devon', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Dorset', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'East Devon', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'East Dorset', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Exeter', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Forest of Dean', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Gloucester', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Isles of Scilly', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Mendip', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Mid Devon', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'North Devon', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'North Somerset', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Plymouth', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Poole', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Purbeck', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Sedgemoor', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'South Hams', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'South Somerset', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Stroud', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Swindon', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Taunton Deane', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Teignbridge', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Tewkesbury', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Torridge', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Torbay', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'West Devon', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'West Dorset', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'West Somerset', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Weymouth and Portland', 'region' => 'South West', 'nation' => 'England'],
        ['name' => 'Wiltshire', 'region' => 'South West', 'nation' => 'England'],

        // Scotland
        ['name' => 'Aberdeen City', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Aberdeenshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Angus', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Argyll and Bute', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Clackmannanshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Dumfries and Galloway', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Dundee City', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'East Ayrshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'East Dunbartonshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'East Lothian', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'East Renfrewshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Edinburgh', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Falkirk', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Fife', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Glasgow City', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Highland', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Inverclyde', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Midlothian', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Moray', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'North Ayrshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'North Lanarkshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Orkney Islands', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Perth and Kinross', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Renfrewshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Scottish Borders', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Shetland Islands', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'South Ayrshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'South Lanarkshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'Stirling', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'West Dunbartonshire', 'region' => 'Scotland', 'nation' => 'Scotland'],
        ['name' => 'West Lothian', 'region' => 'Scotland', 'nation' => 'Scotland'],

        // Wales
        ['name' => 'Anglesey', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Blaenau Gwent', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Bridgend', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Caerphilly', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Cardiff', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Carmarthenshire', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Ceredigion', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Conwy', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Denbighshire', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Flintshire', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Gwynedd', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Merthyr Tydfil', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Monmouthshire', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Neath Port Talbot', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Newport', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Pembrokeshire', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Powys', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Rhondda Cynon Taf', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Swansea', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Torfaen', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Vale of Glamorgan', 'region' => 'Wales', 'nation' => 'Wales'],
        ['name' => 'Wrexham', 'region' => 'Wales', 'nation' => 'Wales'],

        // Northern Ireland
        ['name' => 'Antrim and Newtownabbey', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Ards and North Down', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Armagh City, Banbridge and Craigavon', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Belfast', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Causeway Coast and Glens', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Derry and Strabane', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Fermanagh and Omagh', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Lisburn and Castlereagh', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Mid and East Antrim', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Mid Ulster', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
        ['name' => 'Newry, Mourne and Down', 'region' => 'Northern Ireland', 'nation' => 'Northern Ireland'],
    ];
}
